# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {led_pwm0}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm0}]
set_property PACKAGE_PIN E19 [get_ports {led_pwm1}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm1}]
set_property PACKAGE_PIN U19 [get_ports {led_pwm2}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm2}]
set_property PACKAGE_PIN V19 [get_ports {led_pwm3}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm3}]
set_property PACKAGE_PIN W18 [get_ports {led_pwm4}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm4}]
set_property PACKAGE_PIN U15 [get_ports {led_pwm5}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm5}]
set_property PACKAGE_PIN U14 [get_ports {led_pwm6}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm6}]
set_property PACKAGE_PIN V14 [get_ports {led_pwm7}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm7}]
set_property PACKAGE_PIN V13 [get_ports {led_pwm8}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm8}]
set_property PACKAGE_PIN V3 [get_ports {led_pwm9}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm9}]
set_property PACKAGE_PIN W3 [get_ports {led_pwm10}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm10}]
set_property PACKAGE_PIN U3 [get_ports {led_pwm11}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm11}]
set_property PACKAGE_PIN P3 [get_ports {led_pwm12}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm12}]
set_property PACKAGE_PIN N3 [get_ports {led_pwm13}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm13}]
set_property PACKAGE_PIN P1 [get_ports {led_pwm14}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm14}]
set_property PACKAGE_PIN L1 [get_ports {led_pwm15}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pwm15}]

# Buttons
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
